import = [
  "~/.config/alacritty/colorschemes/atom-one-light.toml",
  "~/.config/alacritty/fonts/jet-brains-mono-nerd-font.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Never"
shape    = "Block"

[keyboard]
bindings = [
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
]

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
decorations     = "full"
dynamic_padding = true
dynamic_title   = true
opacity         = 0.999
startup_mode    = "Windowed"
