[font]
size = 15
normal = { family = "CommitMono", style = "Regular" }
bold = { family = "CommitMono", style = "Bold" }
italic = { family = "CommitMono", style = "Italic" }
bold_italic = { family = "CommitMono", style = "Bold Italic" }
